sudo: false
dist: trusty
language: node_js
node_js:
- 8
install:
- npm install
cache:
  directories:
  - node_modules
script:
- gulp clean
- gulp dist
- gulp verify
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: kj1kIQKA/q8dfziwTYx2Wmyzx1I/7ZcLtb7PaYcFFWtHPApudDKTR6FlhXAdixZhoD+rm3jr7H0uW10pcWY7gSPH4rNGtnocD5gSOKwre6t+81KL2HCVP0lr4T/2QU6rNZKCFMMza+IjC6PkAFns7gO76FrHb593Hhr4vx/PiIg4sCwINurwh6dwWb+ctlo7aeSyDCbZ+DSvtHlvewqtX6sO7kvRLOjDnlQo3YvJscLfZPVrShp1OKMLJgq3GgOSpIwukHyirik7oXkKDIBzHrXTk1MnWz1x7+NGkZA65UkRCOaVbbxCFKdEyvON8Ipg5m4bk4GJR3rCYKobuoNgiPEUi/KJ0Y+HGWadLudIAUd/QM5lYLXASnP7AeV1R4L9vz6tNAWHAUB8/faG1S3h05bDavYJFo33PgHj6LhTLSp7BH91VA9xvGvwyQo4yp25OzbChdGZJumkiG5aVxA38bjB0Y/9lz0VcN1i7dQjsCRAyKvp4SNWYGrj9+sokvsPdISt9WUPNYBgycNIwZaFei67y+rlUINYxYpG9lWEOcq4XHxVI1alLjmgo+qFl99udtexWsow73f1lG/Fgrh0k5wuQdulT3d7v8dBfM4FzVmwgWUNvO1RTpSxPBSlFzQoMWUkQ3WT+m4LRgDCKNnAps+MUBP3xlzyrwAdo9i7jDE=
  on:
    repo: attilanagy/www.attilanagy.net
    branch: master
after_deploy:
- gulp acceptanceTest
branches:
  only:
  - master
